[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "agomax"
version = "0.1.0"
description = "Drone Anomaly Detection Package"
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "pandas",
    "joblib",
    "scikit-learn"
]